macos support for mongodb tools

diff --git a/.local/bin/install_mongodb_tools b/.local/bin/install_mongodb_tools
--- a/.local/bin/install_mongodb_tools
+++ b/.local/bin/install_mongodb_tools
@@ -25,14 +25,34 @@ cleanup_tmp_dirs() {
 }
 trap cleanup_tmp_dirs EXIT
 
+get_os() {
+  local os
+  os=$(uname -s)
+  case $os in
+  Linux)
+    printf "linux"
+    ;;
+  Darwin)
+    printf "macos"
+    ;;
+  *)
+    printf "Unsupported OS: %s\n" "$os" >&2
+    exit 1
+    ;;
+  esac
+}
+
 get_arch() {
   local mode=${1:-standard}
+  local os=${2:-$(get_os)}
   local arch
   arch=$(uname -m)
   case $arch in
   x86_64)
     if [[ $mode == "standard" ]]; then
       printf "x86_64"
+    elif [[ $mode == "archive" && $os == "macos" ]]; then
+      printf "x64"
     else
       printf "x64"
     fi
@@ -49,7 +69,13 @@ get_arch() {
 
 create_tmp_dir() {
   local prefix=$1
-  mktemp -d -p "/tmp" "${prefix}.XXXXXXXXXX"
+  local os
+  os=$(get_os)
+  if [[ $os == "macos" ]]; then
+    mktemp -d -t "${prefix}"
+  else
+    mktemp -d -p "/tmp" "${prefix}.XXXXXXXXXX"
+  fi
 }
 
 version_lt() {
@@ -65,7 +91,8 @@ install_or_update_tool() {
   local url=$2
   local tmp_dir=$3
   local final_dir=$4
-  local archive="$tmp_dir/${tool_name}.tgz"
+  local archive_type="${5:-.tgz}"
+  local archive="$tmp_dir/${tool_name}${archive_type}"
 
   printf "Removing old %s from %s if it exists...\n" "$tool_name" "$final_dir"
   rm -rf "${final_dir:?}"
@@ -73,15 +100,29 @@ install_or_update_tool() {
   printf "Downloading %s from %s...\n" "$tool_name" "$url"
   curl -L -H "$auth_header" -o "$archive" "$url"
 
-  tar --strip-components=1 -xzf "$archive" -C "$tmp_dir"
-
-  if [[ ! -d "$tmp_dir/bin" ]]; then
-    printf "Error: bin/ folder not found after extracting!\n" >&2
-    exit 1
+  if [[ $archive_type == ".zip" ]]; then
+    unzip -q "$archive" -d "$tmp_dir"
+    # Find the extracted directory (could be nested)
+    local extracted_dir
+    extracted_dir=$(find "$tmp_dir" -mindepth 1 -maxdepth 1 -type d | head -n1)
+    if [[ -d "$extracted_dir/bin" ]]; then
+      mkdir -p "$final_dir"
+      mv "$extracted_dir/bin/"* "$final_dir/"
+    elif [[ -d "$extracted_dir" ]]; then
+      # Some archives have binaries directly in the root
+      mkdir -p "$final_dir"
+      find "$extracted_dir" -type f -perm +111 -exec mv {} "$final_dir/" \;
+    fi
+  else
+    tar --strip-components=1 -xzf "$archive" -C "$tmp_dir"
+    if [[ ! -d "$tmp_dir/bin" ]]; then
+      printf "Error: bin/ folder not found after extracting!\n" >&2
+      exit 1
+    fi
+    mkdir -p "$final_dir"
+    mv "$tmp_dir/bin/"* "$final_dir/"
   fi
 
-  mkdir -p "$final_dir"
-  mv "$tmp_dir/bin/"* "$final_dir/"
   chmod +x "$final_dir/"*
 
   printf "%s installed to %s\n\n" "$tool_name" "$final_dir"
@@ -89,8 +130,10 @@ install_or_update_tool() {
 
 install_or_update_mongosh() {
   local final_dir=$1
+  local os
+  os=$(get_os)
   local arch
-  arch=$(get_arch archive)
+  arch=$(get_arch archive "$os")
 
   local version_tag
   version_tag=$(curl -s -H "$auth_header" \
@@ -108,8 +151,18 @@ install_or_update_mongosh() {
     local tmp_dir
     tmp_dir=$(create_tmp_dir mongosh)
     tmp_dirs+=("$tmp_dir")
-    local url="https://github.com/mongodb-js/mongosh/releases/download/${version_tag}/mongosh-${remote_version}-linux-${arch}.tgz"
-    install_or_update_tool mongosh "$url" "$tmp_dir" "$final_dir"
+
+    local url platform_name archive_ext
+    if [[ $os == "macos" ]]; then
+      platform_name="darwin"
+      archive_ext=".zip"
+    else
+      platform_name="linux"
+      archive_ext=".tgz"
+    fi
+
+    url="https://github.com/mongodb-js/mongosh/releases/download/${version_tag}/mongosh-${remote_version}-${platform_name}-${arch}${archive_ext}"
+    install_or_update_tool mongosh "$url" "$tmp_dir" "$final_dir" "$archive_ext"
   else
     printf "mongosh is up to date (%s)\n" "$current_version"
   fi
@@ -117,8 +170,10 @@ install_or_update_mongosh() {
 
 install_or_update_mongodb_tools() {
   local final_dir=$1
+  local os
+  os=$(get_os)
   local arch
-  arch=$(get_arch)
+  arch=$(get_arch standard "$os")
 
   local latest_version
   latest_version=$(curl -s -H "$auth_header" \
@@ -138,8 +193,19 @@ install_or_update_mongodb_tools() {
     local tmp_dir
     tmp_dir=$(create_tmp_dir mongodbtools)
     tmp_dirs+=("$tmp_dir")
-    local url="https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-${arch}-${latest_version}.tgz"
-    install_or_update_tool mongodb-tools "$url" "$tmp_dir" "$final_dir"
+
+    local url platform_name archive_ext
+    if [[ $os == "macos" ]]; then
+      platform_name="macos"
+      archive_ext=".zip"
+      url="https://fastdl.mongodb.org/tools/db/mongodb-database-tools-${platform_name}-${arch}-${latest_version}${archive_ext}"
+    else
+      platform_name="ubuntu2404"
+      archive_ext=".tgz"
+      url="https://fastdl.mongodb.org/tools/db/mongodb-database-tools-${platform_name}-${arch}-${latest_version}${archive_ext}"
+    fi
+
+    install_or_update_tool mongodb-tools "$url" "$tmp_dir" "$final_dir" "$archive_ext"
   else
     printf "mongodb-database-tools are up to date (%s)\n" "$current_version"
   fi
@@ -147,8 +213,10 @@ install_or_update_mongodb_tools() {
 
 install_or_update_atlas_mongo_cli() {
   local final_dir=$1
+  local os
+  os=$(get_os)
   local arch
-  arch=$(get_arch)
+  arch=$(get_arch standard "$os")
 
   local releases_json
   releases_json=$(curl -s -H "$auth_header" \
@@ -172,8 +240,19 @@ install_or_update_atlas_mongo_cli() {
       tmp_dir=$(create_tmp_dir atlascli)
       tmp_dirs+=("$tmp_dir")
       local encoded=${atlas_tag//\//%2F}
-      local url="https://github.com/mongodb/mongodb-atlas-cli/releases/download/${encoded}/mongodb-atlas-cli_${atlas_version}_linux_${arch}.tar.gz"
-      install_or_update_tool atlas-cli "$url" "$tmp_dir" "$final_dir"
+
+      local url platform_name archive_ext
+      if [[ $os == "macos" ]]; then
+        platform_name="macos"
+        archive_ext=".zip"
+        url="https://github.com/mongodb/mongodb-atlas-cli/releases/download/${encoded}/mongodb-atlas-cli_${atlas_version}_${platform_name}_${arch}${archive_ext}"
+      else
+        platform_name="linux"
+        archive_ext=".tar.gz"
+        url="https://github.com/mongodb/mongodb-atlas-cli/releases/download/${encoded}/mongodb-atlas-cli_${atlas_version}_${platform_name}_${arch}${archive_ext}"
+      fi
+
+      install_or_update_tool atlas-cli "$url" "$tmp_dir" "$final_dir" "$archive_ext"
     else
       printf "atlas-cli is up to date (%s)\n" "$current_version"
     fi
