updates and new features

diff --git a/install b/install
--- a/install
+++ b/install
@@ -162,13 +162,14 @@ MISE_PACKAGES_DEBIAN="${MISE_PACKAGES_DEBIAN:-
 "
 MISE_PACKAGES_DEBIAN_EXTRAS="${MISE_PACKAGES_DEBIAN_EXTRAS:-}"
 
-declare -A MISE_LANGUAGES
-MISE_LANGUAGES["node"]="node@22"
-MISE_LANGUAGES["python"]="python@3.13"
-MISE_LANGUAGES["go"]="go@latest"
-MISE_LANGUAGES["java"]="java@corretto-17"
-
-declare -A MISE_LANGUAGES_EXTRAS
+if [[ -z "${MISE_LANGUAGES[*]}" ]]; then
+  declare -gA MISE_LANGUAGES
+  MISE_LANGUAGES["node"]="node@22"
+  MISE_LANGUAGES["python"]="python@3.13"
+  MISE_LANGUAGES["go"]="go@latest"
+  MISE_LANGUAGES["java"]="java@corretto-17"
+fi
+declare -A MISE_LANGUAGES_EXTRAS="${MISE_LANGUAGES_EXTRAS:-}"
 
 OS_TYPE="$(uname | tr "[:upper:]" "[:lower:]")"
 OS_DISTRO=
@@ -231,10 +232,15 @@ EOF
 }
 
 _install_packages_arch() {
-  # shellcheck disable=SC2086
-  sudo pacman -Syu --noconfirm ${PACMAN_PACKAGES} ${PACMAN_PACKAGES_EXTRAS}
+  PACMAN_PACKAGES="$(echo "${PACMAN_PACKAGES}" | xargs)"
+
+  if [[ -n "${PACMAN_PACKAGES}" || -n "${PACMAN_PACKAGES_EXTRAS}" ]]; then
+    # shellcheck disable=SC2086
+    sudo pacman -Syu --noconfirm ${PACMAN_PACKAGES} ${PACMAN_PACKAGES_EXTRAS}
+  fi
 
   # Install Mise packages.
+  MISE_PACKAGES_ARCH="$(echo "${MISE_PACKAGES_ARCH}" | xargs)"
   echo
   # shellcheck disable=SC2086
   if [[ -n "${MISE_PACKAGES_ARCH}" || -n "${MISE_PACKAGES_ARCH_EXTRAS}" ]]; then
@@ -245,16 +251,19 @@ _install_packages_arch() {
 _install_packages_debian() {
   sudo add-apt-repository -y ppa:git-core/ppa
 
-  # shellcheck disable=SC2086
-  sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y ${APT_PACKAGES} ${APT_PACKAGES_EXTRAS}
+  APT_PACKAGES="$(echo "${APT_PACKAGES}" | xargs)"
 
-  sudo apt-get clean && sudo rm -rf /var/lib/apt/lists /var/cache/apt/archives
+  if [[ -n "${APT_PACKAGES}" || -n "${APT_PACKAGES_EXTRAS}" ]]; then
+    # shellcheck disable=SC2086
+    sudo apt-get update && sudo apt-get install -y ${APT_PACKAGES} ${APT_PACKAGES_EXTRAS}
+  fi
 
   # Install Mise packages.
   #
   # Apt's packages typically have older versions since Debian and Ubuntu are
   # stable distros. In most cases the version included is fine but we do want
   # the latest and greatest versions for certain tools.
+  MISE_PACKAGES_DEBIAN="$(echo "${MISE_PACKAGES_DEBIAN}" | xargs)"
   echo
   # shellcheck disable=SC2086
   if [[ -n "${MISE_PACKAGES_DEBIAN}" || -n "${MISE_PACKAGES_DEBIAN_EXTRAS}" ]]; then
@@ -396,10 +405,16 @@ EOF
 }
 
 create_initial_dirs() {
-  mkdir -p "${HOME}/.config/tmux/plugins" "${HOME}/.config/git" "${HOME}/.config/zsh" "${HOME}/.cache/zsh" \
-    "${HOME}/.local/bin" "${HOME}/.local/share"
+  mkdir -p "${HOME}/.config/tmux/plugins" \
+    "${HOME}/.config/git" \
+    "${HOME}/.config/ghostty" \
+    "${HOME}/.config/zsh" \
+    "${HOME}/.cache/zsh" \
+    "${HOME}/.local/bin" \
+    "${HOME}/.local/share"
 
-  mkdir -p "${HOME}/.local/share/zsh/completions" "${HOME}/.aws"
+  mkdir -p "${HOME}/.local/share/zsh/completions" \
+    "${HOME}/.aws"
 }
 
 install_packages() {
@@ -546,6 +561,8 @@ create_symlinks() {
     "ln -fs \"${DOTFILES_PATH}/.config/git/config.user.bitbucket\" \"${HOME}/.config/git/config.user.bitbucket\""
     "ln -fs \"${DOTFILES_PATH}/.config/git/config.user.work\" \"${HOME}/.config/git/config.user.work\""
     "ln -fs \"${DOTFILES_PATH}/.config/gitui\" \"${HOME}/.config/gitui\""
+    "ln -fs \"${DOTFILES_PATH}/.config/ghostty/config\" \"${HOME}/.config/ghostty/config\""
+    "ln -fs \"${DOTFILES_PATH}/.config/ghostty/config.local\" \"${HOME}/.config/ghostty/config.local\""
     "ln -fs \"${DOTFILES_PATH}/.config/nvim\" \"${HOME}/.config/nvim\""
     "ln -fs \"${DOTFILES_PATH}/.local/bin/\"* \"${HOME}/.local/bin/\""
     "ln -fs \"/c/Windows/System32/cmd.exe\" \"${HOME}/.local/bin/cmd.exe\""
@@ -638,6 +655,18 @@ configure_system_configs() {
   echo "Everything that required updating was updated"
 }
 
+configure_home_configs() {
+  _info "CONFIGURE HOME CONFIGS"
+
+  local ghostty_config="${HOME}/.config/ghostty/config.local"
+
+  if [ ! -f "${ghostty_config}" ]; then
+    printf "# Add your custom overrides here, such as fonts, etc..\n" >"${ghostty_config}"
+  fi
+
+  echo "Everything that required updating was updated"
+}
+
 configure_shell() {
   _info "CONFIGURE SHELL (ZSH)"
 
@@ -681,7 +710,15 @@ EOF
     fi
   fi
 
-  [ "${SHELL: -3}" != "zsh" ] && chsh -s "/usr/bin/zsh"
+  # Switch to zsh in a way that supports our supported OS and distros.
+  local shell_path=
+  shell_path="$(which zsh)"
+
+  if ! grep -q "${shell_path}" /etc/shells; then
+    echo "${shell_path}" | sudo tee -a /etc/shells 1>/dev/null
+  fi
+
+  [ "${SHELL: -3}" != "zsh" ] && chsh -s "${shell_path}"
 
   # shellcheck disable=SC1091
   . "${HOME}/.config/zsh/.zprofile"
@@ -814,7 +851,7 @@ install_programming_languages() {
 
   local lang
   for lang in "${!MISE_LANGUAGES[@]}"; do
-    [ -z "${MISE_LANGUAGES[${lang}]}" ] && continue
+    [[ "${lang}" = "0" || -z "${MISE_LANGUAGES[${lang}]}" ]] && continue
 
     printf "\nInstalling %s...\n\n" "${MISE_LANGUAGES[${lang}]}"
     if command -v "${HOME}/.local/share/mise/shims/${lang}" 1>/dev/null; then
@@ -1074,6 +1111,7 @@ install_mongodb_tools
 install_zsh_plugins
 create_symlinks
 configure_system_configs
+configure_home_configs
 configure_shell
 configure_git
 configure_tools
